import "LoopBackManagerContract.idl";

namespace LoopBack.Metadata
{
    [default_interface]
    [contract(LoopBack.Metadata.LoopBackManagerContract, 1)]
    runtimeclass AppContainer : Windows.Foundation.IStringable
    {
        Boolean IsEnableLoop { get; set; };
        String DisplayName { get; set; };
        String AppContainerName { get; set; };
        String PackageFullName{ get; set; };
        String WorkingDirectory { get; set; };
        String AppContainerSid{ get; set; };
        String UserSid{ get; set; };
        Windows.Foundation.Collections.IIterable<String> Capabilities { get; set; };
        Windows.Foundation.Collections.IIterable<String> Binaries{ get; set; };

        AppContainer();
    }
}
