import "LoopBackManagerContract.idl";

namespace LoopBack.Metadata
{
    [default_interface]
    [contract(LoopBackManagerContract, 1)]
    runtimeclass AppContainer : Windows.Foundation.IStringable
    {
        AppContainer();

        Boolean IsEnableLoop { get; set; };
        String DisplayName { get; set; };
        String Description { get; set; };
        String AppContainerName { get; set; };
        String PackageFullName { get; set; };
        String WorkingDirectory { get; set; };
        String AppContainerSid { get; set; };
        String UserSid { get; set; };
        IVector<String> Capabilities { get; set; };
        IVector<String> Binaries { get; set; };
    }

    /// Force midl3 to generate vector marshalling info. 
    declare
    {
        interface IVector<AppContainer>;
        interface IVectorView<AppContainer>;
    }
}
