import "AppContainer.idl";
import "ServerManager.idl";
import "LoopBackManagerContract.idl";

namespace LoopBack.Metadata
{
    [default_interface]
    [contract(LoopBack.Metadata.LoopBackManagerContract, 1)]
    runtimeclass LoopUtil : Windows.Foundation.IClosable
    {
        Windows.Foundation.Collections.IIterable<AppContainer> Apps { get; };

        LoopUtil();
        Windows.Foundation.Collections.IIterable<AppContainer> GetAppContainers();
        Boolean SetLoopbackList(Windows.Foundation.Collections.IIterable<String> list);
        [default_overload]
        Boolean AddLookback(Windows.Foundation.Collections.IIterable<String> list);
        [default_overload]
        Boolean RemoveLookback(Windows.Foundation.Collections.IIterable<String> list);
        Boolean AddLookback(String stringSid);
        Boolean RemoveLookback(String stringSid);
    }
}
