import "AppContainer.idl";
import "ServerManager.idl";
import "LoopBackManagerContract.idl";

namespace LoopBack.Metadata
{
    [default_interface]
    [contract(LoopBackManagerContract, 1)]
    runtimeclass LoopUtil : Windows.Foundation.IClosable
    {
        LoopUtil();

        IVector<AppContainer> Apps { get; };

        IVector<AppContainer> GetAppContainers();
        [default_overload]
        HRESULT SetLoopbackList(IIterable<AppContainer> list);
        [method_name("SetLoopbackListBySid")]
        HRESULT SetLoopbackList(IIterable<String> list);
        [default_overload]
        HRESULT AddLookback(AppContainer appContainer);
        [method_name("AddLookbackBySid")]
        HRESULT AddLookback(String stringSid);
        [default_overload]
        HRESULT AddLookbacks(IIterable<AppContainer> list);
        [method_name("AddLookbacksBySid")]
        HRESULT AddLookbacks(IIterable<String> list);
        [default_overload]
        HRESULT RemoveLookback(AppContainer stringSid);
        [method_name("RemoveLookbackBySid")]
        HRESULT RemoveLookback(String stringSid);
        [default_overload]
        HRESULT RemoveLookbacks(IIterable<AppContainer> list);
        [method_name("RemoveLookbacksBySid")]
        HRESULT RemoveLookbacks(IIterable<String> list);
    }
}
