import "LoopBackManagerContract.idl";
import "LoopUtil.idl";

namespace LoopBack.Metadata
{
    [default_interface]
    [contract(LoopBack.Metadata.LoopBackManagerContract, 1)]
    runtimeclass ServerManager
    {
        ServerManager();

        Boolean IsServerRunning { get; };
        Boolean IsRunAsAdministrator { get; };

        event Windows.Foundation.EventHandler<Boolean> ServerManagerDestructed;

        void RunAsAdministrator();
        LoopBack.Metadata.LoopUtil GetLoopUtil();
        Windows.Foundation.IAsyncAction StopServerAsync();
        Windows.Foundation.IAsyncOperation<LoopBack.Metadata.ServerManager> GetAdminServerManagerAsync();
    }
}
