import "LoopBackManagerContract.idl";
import "LoopUtil.idl";

namespace LoopBack.Metadata
{
    [default_interface]
    [contract(LoopBackManagerContract, 1)]
    runtimeclass ServerManager : Windows.Foundation.IClosable
    {
        ServerManager();

        Boolean IsServerRunning { get; };
        Boolean IsRunAsAdministrator { get; };

        event Windows.Foundation.EventHandler<Boolean> ServerManagerDestructed;

        LoopUtil GetLoopUtil();
        void RunAsAdministrator();
        Windows.Foundation.IAsyncAction StopServerAsync();
        Windows.Foundation.IAsyncOperation<ServerManager> GetAdminServerManagerAsync();
    }
}
