namespace LoopBack.Projection
{
    [default_interface]
    [contract(LoopBack.Metadata.LoopBackManagerContract, 1)]
    static runtimeclass LoopBackProjectionFactory
    {
        static LoopBack.Metadata.ServerManager ServerManager { get; };
    }
}
